### ISSUE TITLE
Viewing longer time periods causes errors

### ISSUE THREAD

**Issue by nopzor1200** [raintank/graphite-kairosdb#10]
(With the latest "direct to Cassandra" code currently in prod)

Dashboards break, seemingly when viewing a time range slightly longer than what the series has data for.

For example, if I view a 5 minute (or 12 hour, or 1-day) range on an OLD endpoint, it works fine.

But after adding a new endpoint, everything is broken even 5 minutes...

Then, after a few minutes the 5 minute period starts working, but all other longer periods remain broken.

Then, after 20 minutes, the 1 hour period starts working. 

Then, after a few hours, the 6 hour period starts working.

Hopefully this is something simple. Other than this bug this is seemingly a big big win in prod (see discussion in Ops).

**Comment by woodsaj** [comment]
fixed in https://github.com/raintank/graphite-kairosdb/commit/91b903017a8400b044468d2d332cf9f14519cb3d
