### ISSUE TITLE
fetch data directly from cassandra

### ISSUE THREAD

**Issue by woodsaj** [raintank/graphite-kairosdb#5]
Kairosdb stores data across 3 tables.  data_points, row_key_index, string_index
see: 
https://code.google.com/p/kairosdb/wiki/CassandraSchema

As we are using ElasticSearch for series lookups, we already know the exact data_points rows that we need. But when querying kairosdb, it still needs to perform the lookups in row_key_index and string_index to determine the matching rows based on the measurement and tags passed in the query.

To improve querying performance we should experiment with fetching data directly from cassandra, bypassing kairosdb.

The data_points row keys are stored as hex strings created in
https://github.com/kairosdb/kairosdb/blob/develop/src/main/java/org/kairosdb/datastore/cassandra/DataPointsRowKeySerializer.java#L57

Eg.
`0x6c69746d75732e70696e672e6d61780000000014e28039400000d6b6169726f735f646f75626c65636f6c6c6563746f723d636f6c6c6563746f723275733a656e64706f696e745f69643d3337363a6d6f6e69746f725f69643d313130383a6f72675f69643d313a`

The key is comprised of the following components.

```
6c69746d75732e70696e672e6d6178 (measurement - "litmus.ping.max")
00 (NUL)
00000014e28039400 (row timestamp - 1435190400000) 
00 (NUL)
0d (dateType size -  15)
6b6169726f735f646f75626c65 (datatype - "kairos_double")
636f6c6c6563746f723d636f6c6c6563746f723275733a656e64706f696e745f69643d3337363a6d6f6e69746f725f69643d313130383a6f72675f69643d313a (tags - "collector=collector2us:endpoint_id=376:monitor_id=1108:org_id=1:")
```

**Comment by Dieterbe** [comment]
does kairosdb expose any sort of metrics on the performance of these individual steps? if not, anyone want to add statsd metrics to kairosdb? :8ball:

**Comment by woodsaj** [comment]
kairosdb does have performance metrics. Though kairos stores them within itself.  You can access the metrics through the kairosdb UI

If kairosdb is not public facing, then just use a ssh tunnel

```
ssh -L8080:localhost:8080 user@host
```

Then browse to localhost:8080 to bring up the kairosdb UI.

**Comment by Dieterbe** [comment]
so it looks like this metric is the applicable:

```
kairosdb.datastore.cassandra.key_query_time - Measures how long it takes to query the row key information.
```

![key-query-time](https://cloud.githubusercontent.com/assets/20774/8679425/7b98e108-2a0f-11e5-94bd-f190dc4eae06.png)
looks like we can shave off quite some time indeed!

this also caught my eye:
![key-query-time-zoom](https://cloud.githubusercontent.com/assets/20774/8679487/c234eda0-2a0f-11e5-9825-e2dfa73bf0f8.png)
it's like there's 2 groups of latencies, perhaps the higher ones it needs to talk to a different machine :?

**Comment by woodsaj** [comment]
This has now been merged into master.

**Comment by Dieterbe** [comment]
do we have before-after measurements? or any indicator of how much this saved us?
