### ISSUE TITLE
can't query periods longer than 13:55:00 anymore

### ISSUE THREAD

**Issue by ctdk** [raintank/graphite-kairosdb#9]
Since updating all of the dev-portal ckg machines to the sparkly new graphite-api with direct cassandra querying, querying periods longer than 13 hours, 55 minutes, and 0 seconds breaks. (Seriously, 13:55:01 breaks). It's not a day boundary thing, either, and I tried it on a variety of different dates, so it doesn't seem to be an issue of bridging datasets.

I assume there must be something significant about 835 minutes or 50100 seconds, but I haven't figured out what it is. Any ideas?

**Comment by woodsaj** [comment]
```
  File "/usr/share/python/graphite/local/lib/python2.7/site-packages/graphite_kairosdb.py", line 192, in fetch_from
_cassandra
    if len(rows) > 0:
TypeError: object of type 'PagedResult' has no len()
```
